#!/usr/bin/env bash
# именование сборки  docker-compose  как "crm_platform" для запуска параллельно с другой сборкой
COMPOSE_PROJECT_NAME=wayprof docker compose -f docker-compose.yml -f docker-compose.override.yml up --remove-orphans
