#!/bin/bash
# на случай если уже есть - удаляем
echo "Clear containers"
docker container rm wayprof_db
docker container rm wayprof_phpfpm
docker container rm wayprof_nginx

echo "Docker Compose"
cd "$(dirname "$0")"
COMPOSE_PROJECT_NAME=wayprof docker compose -f docker-compose.yml -f docker-compose.override.yml build --force-rm --no-cache
